"""Init ORA Core Schema

Revision ID: 12784152ca2c
Revises: 
Create Date: 2026-01-20 17:58:58.083149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '12784152ca2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope', sa.Enum('personal', 'workspace', name='conversationscope'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_scope'), 'conversations', ['scope'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('author', sa.Enum('user', 'assistant', 'tool', 'system', name='authorrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'author', 'idempotency_key', name='uq_msg_idempotency')
    )
    op.create_index(op.f('ix_messages_author'), 'messages', ['author'], unique=False)
    op.create_index('ix_messages_conv_seq', 'messages', ['conversation_id', 'seq'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_run_id'), 'messages', ['run_id'], unique=False)
    op.create_index(op.f('ix_messages_seq'), 'messages', ['seq'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_message_id', sa.String(), nullable=False),
    sa.Column('assistant_message_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'done', 'error', 'canceled', name='runstatus'), nullable=False),
    sa.Column('route', sa.Enum('local_vlm', 'cloud_codex', 'cloud_vision', 'local_text', 'cloud_text', name='runroute'), nullable=True),
    sa.Column('route_reasons', sqlite.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('parent_run_id', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_conversation_id'), 'runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_runs_parent_run_id'), 'runs', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_user_message_id'), 'runs', ['user_message_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_binding_provider_external')
    )
    op.create_index(op.f('ix_conversation_bindings_conversation_id'), 'conversation_bindings', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_bindings_external_id'), 'conversation_bindings', ['external_id'], unique=False)
    op.create_index(op.f('ix_conversation_bindings_provider'), 'conversation_bindings', ['provider'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('client_role', sa.String(length=30), nullable=False),
    sa.Column('permissions', sqlite.JSON(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    op.create_table('tool_invocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(length=60), nullable=False),
    sa.Column('input', sqlite.JSON(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('artifact_ref', sqlite.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_invocations_run_id'), 'tool_invocations', ['run_id'], unique=False)
    op.create_index(op.f('ix_tool_invocations_tool_name'), 'tool_invocations', ['tool_name'], unique=False)
    op.create_table('user_identities',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('auth_metadata', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'provider'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_identity_provider_pid')
    )
    op.create_index(op.f('ix_user_identities_provider_id'), 'user_identities', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identities_provider_id'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index(op.f('ix_tool_invocations_tool_name'), table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_run_id'), table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_conversation_bindings_provider'), table_name='conversation_bindings')
    op.drop_index(op.f('ix_conversation_bindings_external_id'), table_name='conversation_bindings')
    op.drop_index(op.f('ix_conversation_bindings_conversation_id'), table_name='conversation_bindings')
    op.drop_table('conversation_bindings')
    op.drop_table('users')
    op.drop_index(op.f('ix_runs_user_message_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_parent_run_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_conversation_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_messages_seq'), table_name='messages')
    op.drop_index(op.f('ix_messages_run_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conv_seq', table_name='messages')
    op.drop_index(op.f('ix_messages_author'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_scope'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
